kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
spec:
  replicas:
  selector:
    matchLabels:
      app: nginx
      env: bliss-prod
  template:
    metadata:
      name: bliss
      labels:
        app: nginx
        env: bliss-prod
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: bliss
          image: quay.io/robinwu456/bliss_nginx
          imagePullPolicy: Always
